# Yelp Data Challenge - Data Preprocessing

## Dataset Introduction

[Yelp Dataset Challenge](https://www.yelp.com/dataset_challenge)

The Challenge Dataset:

    4.1M reviews and 947K tips by 1M users for 144K businesses
    1.1M business attributes, e.g., hours, parking availability, ambience.
    Aggregated check-ins over time for each of the 125K businesses
    200,000 pictures from the included businesses

Cities:

    U.K.: Edinburgh
    Germany: Karlsruhe
    Canada: Montreal and Waterloo
    U.S.: Pittsburgh, Charlotte, Urbana-Champaign, Phoenix, Las Vegas, Madison, Cleveland

Files:

    yelp_academic_dataset_business.json
    yelp_academic_dataset_checkin.json
    yelp_academic_dataset_review.json
    yelp_academic_dataset_tip.json
    yelp_academic_dataset_user.json

Notes on the Dataset

    Each file is composed of a single object type, one json-object per-line.
    Take a look at some examples to get you started: https://github.com/Yelp/dataset-examples.

## Read data from file and load to Pandas DataFrame

In [5]:
import json
import pandas as pd
import sys
# reload(sys)
# sys.setdefaultencoding('utf-8')

In [6]:
file_business, file_checkin, file_review, file_tip, file_user = [
    './yelp_dataset/yelp_academic_dataset_business.json',
    './yelp_dataset/yelp_academic_dataset_checkin.json',
    './yelp_dataset/yelp_academic_dataset_review.json',
    './yelp_dataset/yelp_academic_dataset_tip.json',
    './yelp_dataset/yelp_academic_dataset_user.json'
]

#### Business Data

In [7]:
with open(file_business) as f:
    df_business = pd.DataFrame(json.loads(line) for line in f)

In [8]:
df_business.head(100)
pd.set_option('display.max_rows',2000)
df_business.city.value_counts()

Las Vegas                                             28865
Phoenix                                               18633
Toronto                                               18233
Charlotte                                              9204
Scottsdale                                             8822
Calgary                                                7384
Pittsburgh                                             6804
Mesa                                                   6239
Montr√©al                                               6045
Henderson                                              4815
Tempe                                                  4492
Chandler                                               4272
Madison                                                3509
Cleveland                                              3506
Glendale                                               3469
Gilbert                                                3397
Mississauga                                            2954
Peoria                                                 1868
Markham                                                1699
North Las Vegas                                        1508
Champaign                                              1243
Scarborough                                            1175
North York                                             1140
Surprise                                               1119
Richmond Hill                                           978
Concord                                                 975
Brampton                                                929
Vaughan                                                 853
Goodyear                                                827
Etobicoke                                               760
Matthews                                                726
Oakville                                                699
Avondale                                                663
Fort Mill                                               620
Huntersville                                            608
Lakewood                                                509
Gastonia                                                494
Cornelius                                               467
Mentor                                                  442
Cave Creek                                              402
Urbana                                                  400
Monroeville                                             390
Westlake                                                379
Thornhill                                               376
North Olmsted                                           373
Laval                                                   373
Strongsville                                            362
Whitby                                                  357
Pineville                                               352
Middleton                                               347
Fountain Hills                                          341
Cuyahoga Falls                                          340
Aurora                                                  336
Medina                                                  327
Newmarket                                               324
Pickering                                               315
Boulder City                                            295
Indian Trail                                            286
Montreal                                                283
Kent                                                    282
Ajax                                                    281
Beachwood                                               281
Wexford                                                 280
Parma                                                   274
Monroe                                                  273
Buckeye                                                 265
Willoughby                                              248
Sun City                                                247
Rocky River                                             246
Sun Prairie                                             244
Woodbridge                                              226
Stow                                                    221
Litchfield Park                                         220
Avon                                                    218
Solon                                                   210
Hudson                                                  201
Cleveland Heights                                       200
Fitchburg                                               199
Bethel Park                                             198
Elyria                                                  198
Verona                                                  195
Airdrie                                                 191
Chagrin Falls                                           186
Bridgeville                                             181
Brunswick                                               178
Coraopolis                                              175
Kannapolis                                              173
Canonsburg                                              171
Waxhaw                                                  167
Brossard                                                166
Belmont                                                 158
Fairlawn                                                156
East York                                               151
Verdun                                                  150
Mayfield Heights                                        149
Tolleson                                                144
North Royalton                                          144
Independence                                            136
Monona                                                  135
MESA                                                    135
Streetsboro                                             132
West Mifflin                                            132
Paradise Valley                                         131
Middleburg Heights                                      130
Saint-Laurent                                           130
Twinsburg                                               127
Painesville                                             127
Gibsonia                                                124
Harrisburg                                              121
Laveen                                                  121
El Mirage                                               119
Berea                                                   118
Avon Lake                                               117
Irwin                                                   117
Homestead                                               117
Sewickley                                               113
Murrysville                                             113
Lyndhurst                                               112
Broadview Heights                                       112
Bedford                                                 111
Stade                                                   110
Stoughton                                               109
York                                                    107
Mint Hill                                               106
Carnegie                                                106
Lorain                                                  106
Davidson                                                103
Euclid                                                  103
Fairview Park                                           102
Amherst                                                 101
Sun City West                                           100
North Ridgeville                                         96
Carefree                                                 96
Macedonia                                                95
Pointe-Claire                                            93
Allison Park                                             93
McMurray                                                 88
Westmount                                                88
Northfield                                               87
Dorval                                                   87
Waunakee                                                 85
New Kensington                                           81
South Euclid                                             81
Lasalle                                                  79
Anthem                                                   78
Brecksville                                              77
Savoy                                                    77
Chardon                                                  77
Brooklyn                                                 77
Oregon                                                   72
Longueuil                                                72
Parma Heights                                            71
San Tan Valley                                           71
Eastlake                                                 67
Indian Land                                              67
Chesterland                                              67
Tallmadge                                                65
McKeesport                                               63
Willowick                                                63
Vaudreuil-Dorion                                         62
McKees Rocks                                             62
Youngtown                                                62
Shaker Heights                                           61
Dollard-des-Ormeaux                                      60
Maple                                                    59
Woodmere                                                 57
North Versailles                                         57
North Huntingdon                                         57
Mount Horeb                                              55
Stouffville                                              55
Brook Park                                               53
Frazer                                                   52
Saint-Sauveur                                            52
Rantoul                                                  50
Oakmont                                                  50
Lake Wylie                                               49
Lachine                                                  48
Pierrefonds                                              48
Georgetown                                               48
Mount Holly                                              47
Olmsted Falls                                            47
Willoughby Hills                                         46
Dollard-Des-Ormeaux                                      46
Garfield Heights                                         46
Warrensville Heights                                     45
Unionville                                               45
Maple Heights                                            45
Glenshaw                                                 45
Oakdale                                                  44
Whitchurch-Stouffville                                   44
Mahomet                                                  43
Richfield                                                43
University Heights                                       42
Bay Village                                              40
Ambridge                                                 40
Wickliffe                                                39
Mc Kees Rocks                                            39
Moon Township                                            39
Saint-Leonard                                            39
Highland Heights                                         39
Caledon                                                  38
Kirkland                                                 38
Bellevue                                                 38
Cottage Grove                                            38
Trafford                                                 38
las vegas                                                37
Bolton                                                   37
Outremont                                                37
Pleasant Hills                                           34
Chestermere                                              34
Seven Hills                                              33
Copley                                                   33
WICKLIFFE                                                33
Middlefield                                              33
Monticello                                               33
White Oak                                                32
Mc Farland                                               31
Dallas                                                   31
Bellagio                                                 30
Tega Cay                                                 30
McFarland                                                30
Tuscola                                                  30
Sun Lakes                                                30
Mont-Royal                                               30
Bradford                                                 29
Landsberg                                                29
Penn Hills                                               29
Boucherville                                             29
DeForest                                                 28
Elizabeth                                                28
Munhall                                                  28
Olivos                                                   28
Peninsula                                                27
Sheffield Village                                        27
Thale                                                    27
Cheswick                                                 27
De Forest                                                27
Burton                                                   26
Higley                                                   26
East Gwillimbury                                         26
Saint-Jean-sur-Richelieu                                 26
Fairview                                                 24
Paradise                                                 24
Jork                                                     24
Richmond Heights                                         24
Guadalupe                                                23
N Las Vegas                                              23
Cross Plains                                             23
Bedford Heights                                          23
Monongahela                                              23
Stallings                                                23
Lower Burrell                                            23
Saint-Hubert                                             22
Robinson Township                                        22
Valley View                                              22
Wesley Chapel                                            21
Finleyville                                              21
Kirtland                                                 21
Midland                                                  21
Hinckley                                                 20
King City                                                20
Turtle Creek                                             20
Saint-Lambert                                            20
Vanier                                                   20
Aspinwall                                                20
Chateauguay                                              19
Pepper Pike                                              19
West Homestead                                           19
Imperial                                                 19
Laveen Village                                           18
Brentwood                                                18
Newbury                                                  18
Bradford West Gwillimbury                                18
Mantua                                                   18
Lich                                                     18
Munroe Falls                                             18
Rocky View                                               18
Anjou                                                    18
Saint-Jerome                                             17
Plum                                                     17
Clairton                                                 17
Mayfield                                                 17
Waddell                                                  17
Saint-Eustache                                           17
Ahwatukee                                                17
Brookpark                                                17
Stanley                                                  17
La Prairie                                               17
Grafton                                                  16
Sainte-Julie                                             16
West View                                                16
Saint Joseph                                             16
Terrebonne                                               15
Greenfield Park                                          15
Boisbriand                                               15
Windsor                                                  15
Fort McDowell                                            15
Millvale                                                 15
Belleville                                               15
Clark                                                    15
Rosemere                                                 14
Mount Lebanon                                            14
Gr√ºnberg                                                 14
Springdale                                               14
Lowell                                                   14
Castle Shannon                                           14
Cramerton                                                13
Sheffield Lake                                           13
Leetsdale                                                13
Jefferson Hills                                          13
Sainte-Anne-De-Bellevue                                  13
Chambly                                                  13
Bainbridge                                               13
Blue Diamond                                             12
Balzac                                                   12
Etna                                                     12
Heidelberg                                               12
Beloeil                                                  12
Wilkinsburg                                              12
Columbia Station                                         12
Valley City                                              12
Beaconsfield                                             11
Sainte-Anne-de-Bellevue                                  11
Dravosburg                                               11
Angus                                                    11
N. Las Vegas                                             11
Nellis Afb                                               11
Sainte-Adele                                             11
Oakwood Village                                          11
Brooklin                                                 11
Oakwood                                                  11
Weddington                                               11
Moss                                                     11

In [9]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188593 entries, 0 to 188592
Data columns (total 15 columns):
address         188593 non-null object
attributes      162807 non-null object
business_id     188593 non-null object
categories      188052 non-null object
city            188593 non-null object
hours           143791 non-null object
is_open         188593 non-null int64
latitude        188587 non-null float64
longitude       188587 non-null float64
name            188593 non-null object
neighborhood    188593 non-null object
postal_code     188593 non-null object
review_count    188593 non-null int64
stars           188593 non-null float64
state           188593 non-null object
dtypes: float64(3), int64(2), object(10)
memory usage: 21.6+ MB

#### Check-in Data

In [10]:
with open(file_checkin) as f:
    df_checkin = pd.DataFrame(json.loads(line) for line in f)
df_checkin.head(2)

              business_id                                               time
0  7KPBkxAOEtb3QeIL9PEErg  {'Fri-0': 2, 'Sat-0': 1, 'Sun-0': 1, 'Wed-0': ...
1  kREVIrSBbtqBhIYkTccQUg  {'Mon-13': 1, 'Thu-13': 1, 'Sat-16': 1, 'Wed-1...

#### Review Data

In [11]:
with open(file_review) as f:
    df_review = pd.DataFrame(json.loads(line) for line in f)
df_review.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,iCQpiavjjPzJ5_3gPD5Ebg,0,2011-02-25,0,x7mDIiDB3jEiPGPHOmDzyw,2,The pizza was okay. Not the best I've had. I p...,0,msQe1u7Z_XuqjGoqhB0J5g
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g

#### Tip Data

In [12]:
with open(file_tip) as f:
    df_tip = pd.DataFrame(json.loads(line) for line in f)
df_tip.head(2)

,business_id,date,likes,text,user_id
0,tJRDll5yqpZwehenzE2cSg,2012-07-15,0,Get here early enough to have dinner.,zcTZk7OG8ovAmh_fenH21g
1,2ThtBbeDqFkVi6LugUOcVA,2012-11-25,0,Don't use them! Double charged my boyfriend an...,M5n8mMFoeXjnJEV2gxyGGA

#### User Data

In [13]:
with open(file_user) as f:
    df_user = pd.DataFrame(json.loads(line) for line in f)

In [14]:
df_user.head(10)

,average_stars,compliment_cool,compliment_cute,compliment_funny,compliment_hot,compliment_list,compliment_more,compliment_note,compliment_photos,compliment_plain,...,cool,elite,fans,friends,funny,name,review_count,useful,user_id,yelping_since
0,2.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Susan,1,0,lzlZwIpuSWXEnNS91wxjHw,2015-09-28
1,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Daipayan,2,0,XvLBr-9smbI0m_a7dXtB7w,2015-09-05
2,4.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Andy,1,0,QPT4Ud4H5sJVr68yXhoWFw,2016-07-21
3,4.05,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Jonathan,19,0,i5YitlHZpf0B3R0s_8NVuw,2014-08-04
4,3.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Shashank,3,0,s4FoIXE_LSGviTHBe8dmcg,2017-06-18
5,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Stacey X Joe,3,0,ZcsZdHLiJGVvDHVjeTYYnQ,2014-08-27
6,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Lindsay,2,0,h3p6aeVL7vrafSOM50SsCg,2016-02-02
7,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Joshua,1,0,EbJMotYYkq-iq-v1u8wCYA,2013-03-20
8,2.77,0,0,0,0,0,0,0,0,0,...,0,None,1,None,0,Mike,11,8,nnB0AE1Cxp_0154xkhXelw,2014-07-11
9,4.00,0,0,0,0,0,0,0,0,0,...,1,None,0,None,3,Mitch,4,2,XoEnrhtJc2pcdlQ09d8Oug,2013-04-07

## Filter data by city and category

I am interested in the Yelp business in Canada due to large amount of visitors and resturants. Thus, I create filters that selects business 
* that are located in "Toronto" etc.
* that contains "Restaurants" in their category

In [15]:
df_filtered = df_business[(df_business['city'] == "Toronto") | (df_business['city'] == "Calgary")
                         |(df_business['city'] == "Montr√©al") |(df_business['city'] == "Mississauga")
                          |(df_business['city'] == "Markham")|(df_business['city'] == "Chandler")
                          |(df_business['city'] == "Scarborough")|(df_business['city'] == "Scarborough")
                          |(df_business['city'] == "Etobicoke")|(df_business['city'] == "Oakville")]

In [16]:
df_filtered = df_filtered[df_filtered['categories'].str.contains("Restaurants",na=False)]
df_filtered.head(2)
#"Restaurants" in category #for category in df_filtered['categories']
#df_Toronto_Restaurants=df_filtered['Restaurants' in df_filtered['categories']]
#df_Toronto_Restaurants

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state
0,1314 44 Avenue NE,"{'BikeParking': 'False', 'BusinessAcceptsCredi...",Apn5Q_b6Nz61Tq4XzPdf9A,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",Calgary,"{'Monday': '8:30-17:0', 'Tuesday': '11:0-21:0'...",1,51.091813,-114.031675,Minhas Micro Brewery,,T2E 6L6,24,4.0,AB
2,1335 rue Beaubien E,"{'Alcohol': 'beer_and_wine', 'Ambience': '{'ro...",O8S5hYJ1SMc8fA4QBtVujA,"Breakfast & Brunch, Restaurants, French, Sandw...",Montr√©al,"{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",0,45.540503,-73.599300,La Bastringue,Rosemont-La Petite-Patrie,H2G 1K7,5,4.0,QC

#### Keep relevant columns

* only keep some useful columns
    * business_id
    * name
    * categories
    * stars

In [17]:
selected_features = [u'business_id', u'name', u'categories', u'stars']
df_selected_business = df_filtered[selected_features]
df_selected_business.head(2)

,business_id,name,categories,stars
0,Apn5Q_b6Nz61Tq4XzPdf9A,Minhas Micro Brewery,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",4.0
2,O8S5hYJ1SMc8fA4QBtVujA,La Bastringue,"Breakfast & Brunch, Restaurants, French, Sandw...",4.0

#### Rename the column name "stars" to "avg_stars" to avoid naming conflicts with review dataset

In [18]:
df_selected_business = df_selected_business.rename(columns = {'stars':'avg_stars'})
df_selected_business.head(2)

,business_id,name,categories,avg_stars
0,Apn5Q_b6Nz61Tq4XzPdf9A,Minhas Micro Brewery,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",4.0
2,O8S5hYJ1SMc8fA4QBtVujA,La Bastringue,"Breakfast & Brunch, Restaurants, French, Sandw...",4.0

#### Save results to csv files

In [19]:
#f.write(printinfo.encode('utf8') + '\n')
df_selected_business.to_csv('./business.csv', index_label=False)

### Use the "business_id" column to filter review data

* I want to make a DataFrame that contain and only contain the reviews about the business entities I just obtained

#### Prepare dataframes to be joined on business_id

In [20]:
df_left = df_selected_business.set_index('business_id')
df_left.head(2)

,name,categories,avg_stars
business_id,,,
Apn5Q_b6Nz61Tq4XzPdf9A,Minhas Micro Brewery,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",4.0
O8S5hYJ1SMc8fA4QBtVujA,La Bastringue,"Breakfast & Brunch, Restaurants, French, Sandw...",4.0

In [21]:
df_left.head(10)

,name,categories,avg_stars
business_id,,,
Apn5Q_b6Nz61Tq4XzPdf9A,Minhas Micro Brewery,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",4.0
O8S5hYJ1SMc8fA4QBtVujA,La Bastringue,"Breakfast & Brunch, Restaurants, French, Sandw...",4.0
6OuOZAok8ikONMS_T3EzXg,Thai One On,"Restaurants, Thai",2.0
KapTdGyGs7RK0c68Z6hhhg,Sushi 8,"Restaurants, Japanese",1.5
tZnSodhPwNr4bzrwJ1CSbw,Southern Accent Restaurant,"Cajun/Creole, Southern, Restaurants",4.0
bBUMib8l6Me1ZB1_Qkezkg,Mysore Indian Cuisine,"Restaurants, Pakistani, Indian, Middle Eastern",3.5
IbTDLI02Sq50C7B-EWK1sg,Safeway Food & Drug,"Delis, Restaurants, Sandwiches",2.5
r89Re4FNgVWHgBfjCVZyVw,Harlow,"Nightlife, Bars, American (Traditional), Tapas...",3.5
PMDlKLd0Mxj0ngCpuUmE5Q,The Coffee Mill Restaurant,"Restaurants, Food, Canadian (New), Coffee & Tea",3.5
YIez_A3WOt9J2SXN7OMa2Q,Allwyn's Bakery,"Caribbean, Food, Bakeries, Restaurants",4.0

In [22]:
df_right = df_review.set_index('business_id')

In [23]:
df_right.head(10)

,cool,date,funny,review_id,stars,text,useful,user_id
business_id,,,,,,,,
iCQpiavjjPzJ5_3gPD5Ebg,0,2011-02-25,0,x7mDIiDB3jEiPGPHOmDzyw,2,The pizza was okay. Not the best I've had. I p...,0,msQe1u7Z_XuqjGoqhB0J5g
pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
elqbBhBfElMNSrjFqW3now,0,2011-02-25,0,Er4NBWCmCD4nM8_p1GRdow,2,Back in 2005-2007 this place was my FAVORITE t...,2,msQe1u7Z_XuqjGoqhB0J5g
Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
AxeQEz3-s9_1TyIo-G7UQw,0,2011-10-10,0,brokEno2n7s4vrwmmUdr9w,5,"If you like Thai food, you have to try the ori...",1,msQe1u7Z_XuqjGoqhB0J5g
zdE82PiD6wquvjYLyhOJNA,0,2012-04-18,1,kUZWBVZvhWuC8TWUg5AYyA,5,AMAZING!!!\n\n I was referred here by a friend...,0,msQe1u7Z_XuqjGoqhB0J5g
EAwh1OmG6t6p3nRaZOW_AA,0,2011-02-25,0,wcqt0III88LEcm19IxFFyA,4,Ribs = amazing\n2 hour wait time= not so amazi...,0,msQe1u7Z_XuqjGoqhB0J5g
atVh8viqTj-sqDJ35tAYVg,1,2012-11-09,2,LWUtqzNthMM3vpWZIFBlPw,2,"Food is pretty good, not gonna lie. BUT you ha...",1,msQe1u7Z_XuqjGoqhB0J5g

#### Join two tables and reset index

In [24]:
df_combine = df_left.join(df_right, how = "left")
df_combine.shape

(672196, 11)

In [25]:
df_combine = df_combine.reset_index()

In [26]:
df_combine.head(10)

,business_id,name,categories,avg_stars,cool,date,funny,review_id,stars,text,useful,user_id
0,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2016-07-25,0,0tFxHz2j1GJ8-IYPp5NxWA,4,Came here for lunch last week and was pleasant...,0,t4cYW73lVcBb-1R_Wms1RQ
1,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2016-12-06,0,KByp3bKAt9GMqU7koJ8htg,5,If you want Mexican for a reasonable price in ...,0,hqk4eugYhjmhM-3S2FwGjA
2,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-12-12,0,e1HiHHD7CzY5NKZG7hvhTw,5,Absolutely delicious! And great service as wel...,0,Sew1Nht6Q0sGTIZeNvRfLw
3,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-08-09,0,oKm8UTv-QSC0oCbniqwxjg,4,"Tasty, authentic Mexican street food that give...",0,NoQCmYKyMPs4D01Wa6dZew
4,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2016-07-16,0,-i9u19L08A4VvhFVfqXK9Q,5,First time here since it changed ownership. Ha...,0,qUnvyCfCpr9ZG_F5oezJMw
5,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2017-05-10,0,9CLEOpUCqRkIR02sx-JsMQ,5,A little hole in the wall for some really deli...,0,atyCaAjUYatIFDOGKy00SA
6,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-01-11,0,hhVr1uH7XaRlbIHI8dYvbA,5,Glad these guys moved in on the block! It's qu...,0,FYhU1fKQ7n11WQ7gcFYOag
7,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-04-22,0,BIecLw546kAlD7kmlk7vXA,2,I have been in search of good grilled steak ta...,0,sTVGcezME7gYBhIlYtcfpg
8,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2016-09-07,0,Xm_X1joceDpZIxLdUZlP-g,5,In my last review I mentioned getting charged ...,0,brd33PD_6nqK_VVnO3NWAg
9,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2016-08-16,0,8UsalYi1Jkbk8WitFEa_aQ,4,Spicy Amigos is the old Jalape√±os. I'm not sur...,0,1b4rlFFdNfeysOjbrFykng

#### I further filter data by date to keep comments in 2017
* Otherwise my laptop may crush on memory when running machine learning algorithms
* Purposefully ignoring the reviews made too long time ago

In [27]:
# Make a filter that selects date after 2017-01-20
df_combine['date'] = pd.to_datetime(df_combine['date'], format = "%Y-%m-%d")
cut_off = pd.to_datetime("2017-01-01", format = "%Y-%m-%d")
# Filter the joined DataFrame and name it as df_final
df_final = df_combine[df_combine['date'] > cut_off]

In [28]:
df_final.head(10)

,business_id,name,categories,avg_stars,cool,date,funny,review_id,stars,text,useful,user_id
2,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-12-12,0,e1HiHHD7CzY5NKZG7hvhTw,5,Absolutely delicious! And great service as wel...,0,Sew1Nht6Q0sGTIZeNvRfLw
3,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-08-09,0,oKm8UTv-QSC0oCbniqwxjg,4,"Tasty, authentic Mexican street food that give...",0,NoQCmYKyMPs4D01Wa6dZew
5,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2017-05-10,0,9CLEOpUCqRkIR02sx-JsMQ,5,A little hole in the wall for some really deli...,0,atyCaAjUYatIFDOGKy00SA
6,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-01-11,0,hhVr1uH7XaRlbIHI8dYvbA,5,Glad these guys moved in on the block! It's qu...,0,FYhU1fKQ7n11WQ7gcFYOag
7,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-04-22,0,BIecLw546kAlD7kmlk7vXA,2,I have been in search of good grilled steak ta...,0,sTVGcezME7gYBhIlYtcfpg
12,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,2,2017-05-01,1,ZULaTgcgMFJ4SHo_9ZcgxQ,5,Fantastic spot for lunch with great value for ...,2,ZS_qdLMh1XyXKGTrpKM-4Q
13,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-12-23,0,EiJoov0ZiIeAB527KizL5Q,5,This is our first time here with the renovatio...,0,P3V5p1Wt3znW2-4YtgafbA
14,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-07-26,0,X4PwY0mMHxqOf2O1pwYdIQ,5,"Delicious! One of the best burritos, salsa and...",0,4YHZzwlxEMi7zWO6Osszdw
16,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-04-03,0,Ueb33Y77jRDQhkjf7nmCUw,5,"We were in the mood for tacos, and came across...",0,Le81nQXs_LwAxRk9eK8oQQ
17,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-08-27,0,UfKXTOleA4mtNOOMqzCBTQ,4,"Friendly, fresh, authentic Mexican food for a ...",0,ncf_USO7wFU-B5bJjBkt9w

## Save my preprocessed dataset to csv file

In [29]:
df_final.to_csv('./2017_restaurant_reviews.csv', index_label=False)
df_final = pd.read_csv('./2017_restaurant_reviews.csv')

In [30]:
df_final.head(10)

,business_id,name,categories,avg_stars,cool,date,funny,review_id,stars,text,useful,user_id
2,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-12-12,0,e1HiHHD7CzY5NKZG7hvhTw,5,Absolutely delicious! And great service as wel...,0,Sew1Nht6Q0sGTIZeNvRfLw
3,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-08-09,0,oKm8UTv-QSC0oCbniqwxjg,4,"Tasty, authentic Mexican street food that give...",0,NoQCmYKyMPs4D01Wa6dZew
5,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,1,2017-05-10,0,9CLEOpUCqRkIR02sx-JsMQ,5,A little hole in the wall for some really deli...,0,atyCaAjUYatIFDOGKy00SA
6,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-01-11,0,hhVr1uH7XaRlbIHI8dYvbA,5,Glad these guys moved in on the block! It's qu...,0,FYhU1fKQ7n11WQ7gcFYOag
7,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2018-04-22,0,BIecLw546kAlD7kmlk7vXA,2,I have been in search of good grilled steak ta...,0,sTVGcezME7gYBhIlYtcfpg
12,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,2,2017-05-01,1,ZULaTgcgMFJ4SHo_9ZcgxQ,5,Fantastic spot for lunch with great value for ...,2,ZS_qdLMh1XyXKGTrpKM-4Q
13,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-12-23,0,EiJoov0ZiIeAB527KizL5Q,5,This is our first time here with the renovatio...,0,P3V5p1Wt3znW2-4YtgafbA
14,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-07-26,0,X4PwY0mMHxqOf2O1pwYdIQ,5,"Delicious! One of the best burritos, salsa and...",0,4YHZzwlxEMi7zWO6Osszdw
16,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-04-03,0,Ueb33Y77jRDQhkjf7nmCUw,5,"We were in the mood for tacos, and came across...",0,Le81nQXs_LwAxRk9eK8oQQ
17,--1UhMGODdWsrMastO9DZw,The Spicy Amigos,"Restaurants, Mexican",4.0,0,2017-08-27,0,UfKXTOleA4mtNOOMqzCBTQ,4,"Friendly, fresh, authentic Mexican food for a ...",0,ncf_USO7wFU-B5bJjBkt9w